name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://alpine:3.8
    - name: Build the Docker image
      run: |
          docker-compose build
          docker-compose up -d
